my_blog/data/urls.py
from django.conf.urls import url

from . import views

app_name = 'data'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^api/sum_by_sex_year', views.sum_by_sex_year, name='sum_by_sex_year'),
    url(r'^api/(?P<baby_name>[a-zA-Z]+)/sum_by_sex_year/$', views.name_sum_by_year, name='name_sum_by_year'),
]

my_blog/myblog/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtailcore import urls as wagtail_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls

from search import views as search_views

from . import views


urlpatterns = [
    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'^music/', views.music),
    url(r'^resume/', views.resume),
    url(r'^data/', include('data.urls')),
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
    
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/data/models.py
from django.db import models

# Create your models here.

class Babynames2(models.Model):
    year = models.FloatField(blank=True, null=True)
    sex = models.TextField(blank=True, null=True)
    name = models.TextField(blank=True, null=True)
    n = models.IntegerField(blank=True, null=True)
    prop = models.FloatField(blank=True, null=True)
    id = models.AutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'babynames2'

my_blog/home/models.py
from __future__ import absolute_import, unicode_literals

from django.db import models

from modelcluster.fields import ParentalKey

from wagtail.wagtailcore.models import Page, Orderable
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailadmin.edit_handlers import FieldPanel, InlinePanel
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel
from wagtail.wagtailsearch import index


class HomePage(Page):
    date = models.DateField("Post date")
    intro = models.CharField(max_length=250)
    body = RichTextField(blank=True)

    def main_image(self):
        gallery_item = self.gallery_images.first()
        if gallery_item:
            return gallery_item.image
        else:
            return None
            
    search_fields = Page.search_fields + [
        index.SearchField('intro'),
        index.SearchField('body'),
    ]

    content_panels = Page.content_panels + [
        FieldPanel('date'),
        FieldPanel('intro'),
        FieldPanel('body', classname="full"),
        InlinePanel('gallery_images', label="Gallery images"),
    ]

class HomeIndexPage(Page):
    intro = RichTextField(blank=True)

    def get_context(self, request):
        # Update context to include only published posts, ordered by reverse-chron
        context = super(HomeIndexPage, self).get_context(request)
        blogpages = self.get_children().live().order_by('-first_published_at')
        context['blogpages'] = blogpages
        return context

    content_panels = Page.content_panels + [
        FieldPanel('intro', classname="full")
    ]

class TravelPageGalleryImage(Orderable):
    page = ParentalKey(HomePage, related_name='gallery_images')
    image = models.ForeignKey(
        'wagtailimages.Image', on_delete=models.CASCADE, related_name='+'
    )
    caption = models.CharField(blank=True, max_length=250)

    panels = [
        ImageChooserPanel('image'),
        FieldPanel('caption'),
    ]

my_blog/data/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .models import Babynames2
#from django.template import loader
from django.http import JsonResponse
from django.db.models import Sum
from django.shortcuts import get_object_or_404, render

def index(request):

    #firstFive = Babynames2.objects.only('name')[:1000]
    
    
    #context = {'firstFive': firstFive}

    #return render(request, 'data/data.html', context)
    return render(request, 'data/data_name.html')

def sum_by_sex_year(request):
    #data = Babynames2.objects.values('year', 'sex').annotate(total = Sum('n')).order_by('year')
    data = Babynames2.objects.values('year').annotate(total = Sum('n')).order_by('year')
    return JsonResponse(list(data), safe=False)


def name_sum_by_year(request, baby_name):
    data = Babynames2.objects.filter(name = baby_name).values('year').annotate(total = Sum('n')).order_by('year')
    return JsonResponse(list(data), safe=False)

my_blog/myblog/views.py
from django.shortcuts import render

def music(request):
    return render(request, 'music.html')


def resume(request):
    return render(request, 'resume.html')

my_blog/search/views.py
from __future__ import absolute_import, unicode_literals

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render

from wagtail.wagtailcore.models import Page
from wagtail.wagtailsearch.models import Query


def search(request):
    search_query = request.GET.get('query', None)
    page = request.GET.get('page', 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)

        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return render(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': search_results,
    })

my_blog/data/templates/data/data.html
{% extends 'base.html' %}

{% block content %}
{% if firstFive %}
<ul>
{% for dt in firstFive %}
    <!--Removing hardcoded URLs in templates
    <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>  
    -->
    <li>{{ dt.name }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No data is available.</p>
{% endif %}
{% endblock %}

my_blog/data/templates/data/data2.html
<!DOCTYPE html>
<meta charset="utf-8">
<style>

body {
  font: 10px sans-serif;
}

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.x.axis path {
  display: none;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 1.5px;
}

</style>
<body>
<svg width="960" height="500"></svg>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script>

var svg = d3.select("svg"),
    margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = +svg.attr("width") - margin.left - margin.right,
    height = +svg.attr("height") - margin.top - margin.bottom,
    g = svg.append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");

//var parseDate = d3.time.format("%Y-%m-%d").parse; // for dates like "2014-01-01"
//var parseDate = d3.time.format("%Y-%m-%dT00:00:00Z").parse;  // for dates like "2014-01-01T00:00:00Z"
var parseTime = d3.timeParse("%Y");

var x = d3.scaleTime()
    .rangeRound([0, width]);

var y = d3.scaleLinear()
    .rangeRound([height, 0]);

var line = d3.line()
    .x(function(d) { return x(d.year); })
    .y(function(d) { return y(d.total); });


d3.json("{% url 'data:sum_by_sex_year' %}", function(error, data) {
  data.forEach(function(d) {
    d.year = parseTime(d.year);
    d.total = +d.total;
  });

  x.domain(d3.extent(data, function(d) { return d.year; }));
  y.domain(d3.extent(data, function(d) { return d.total; }));

g.append("g")
    .attr("transform", "translate(0," + height + ")")
    .call(d3.axisBottom(x))
    .select(".domain")
    .remove();

g.append("g")
    .call(d3.axisLeft(y))
    .append("text")
    .attr("fill", "#000")
    .attr("transform", "rotate(-90)")
    .attr("y", 6)
    .attr("dy", "0.71em")
    .attr("text-anchor", "end")
    .text("Price ($)");

g.append("path")
  .datum(data)
  .attr("fill", "none")
  .attr("stroke", "steelblue")
  .attr("stroke-linejoin", "round")
  .attr("stroke-linecap", "round")
  .attr("stroke-width", 1.5)
  .attr("d", line);
});

</script>
</body>
</html>

my_blog/data/templates/data/data_bkp.html
<!DOCTYPE html>
<meta charset="utf-8">
<style>

body {
  font: 10px sans-serif;
}

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.x.axis path {
  display: none;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 1.5px;
}

</style>
<body>
<script src="http://d3js.org/d3.v3.js"></script>
<script>

var margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

//var parseDate = d3.time.format("%Y-%m-%d").parse; // for dates like "2014-01-01"
//var parseDate = d3.time.format("%Y-%m-%dT00:00:00Z").parse;  // for dates like "2014-01-01T00:00:00Z"
var parseDate = d3.time.format("%Y").parse;

var x = d3.time.scale()
    .range([0, width]);

var y = d3.scale.linear()
    .range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");

var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left");

var line = d3.svg.line()
    .x(function(d) { return x(d.year); })
    .y(function(d) { return y(d.total); });

var svg = d3.select("body").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

d3.json("{% url 'data:sum_by_sex_year' %}", function(error, data) {
  data.forEach(function(d) {
    d.year = parseDate(d.year);
    d.total = +d.total;
  });

  x.domain(d3.extent(data, function(d) { return d.year; }));
  y.domain(d3.extent(data, function(d) { return d.total; }));

  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis);

  svg.append("g")
      .attr("class", "y axis")
      .call(yAxis)
    .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Play count");

  svg.append("path")
      .datum(data)
      .attr("class", "line")
      .attr("d", line);
});

</script>
</body>
</html>

my_blog/data/templates/data/data_name.html
<!DOCTYPE html>
<meta charset="utf-8">
<style>

body {
  font: 10px sans-serif;
}

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.x.axis path {
  display: none;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 1.5px;
}

</style>
<body>
<p>
    <label for="your_name">Baby name: </label>
    <input id="your_name" type="text" name="your_name" value="Daniel">
    <input type="submit" value="OK">
</p>
<svg width="960" height="500"></svg>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script
src="https://code.jquery.com/jquery-3.2.1.min.js"
integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
crossorigin="anonymous"></script>
<script>
    var svg = d3.select("svg"),
    margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = +svg.attr("width") - margin.left - margin.right,
    height = +svg.attr("height") - margin.top - margin.bottom,
    g = svg.append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");
    

    //var parseDate = d3.time.format("%Y-%m-%d").parse; // for dates like "2014-01-01"
    //var parseDate = d3.time.format("%Y-%m-%dT00:00:00Z").parse;  // for dates like "2014-01-01T00:00:00Z"
    var parseTime = d3.timeParse("%Y");

    var x = d3.scaleTime()
        .rangeRound([0, width]);

    var y = d3.scaleLinear()
        .rangeRound([height, 0]);

    var line = d3.line()
        .x(function(d) { return x(d.year); })
        .y(function(d) { return y(d.total); });

    //console.log(babyname);
    //console.log(updated_url);

    $(document).ready(function() {

        $('#your_name').keyup(function() {
            //console.log($(this).val());
            //console.log(updated_url);
            $.ajax({

                // The URL for the request
                url: 'api/' + $(this).val() + '/sum_by_sex_year/',

                // The data to send (will be converted to a query string)
                //data: {
                //    id: 123
                //},

                // Whether this is a POST or GET request
                type: "GET",

                // The type of data we expect back
                dataType : "json",
                })
                // Code to run if the request succeeds (is done);
                // The response is passed to the function
                .done(function( json ) {
                    //console.log( json );
                    var post_data = json;
                    drawChart(post_data);
                })
                // Code to run if the request fails; the raw request and
                // status codes are passed to the function
                //.fail(function( xhr, status, errorThrown ) {
                //    alert( "Sorry, there was a problem!" );
                //    console.log( "Error: " + errorThrown );
                //    console.log( "Status: " + status );
                //    console.dir( xhr );
                //})
                // Code to run regardless of success or failure;
                //.always(function( xhr, status ) {
                //    alert( "The request is complete!" );
        });
    });

function drawChart(data){

    for(var i = 0; i < data.length; i++) {
        data[i]['year'] = parseTime(data[i]['year']);
    }

    d3.selectAll("g > *").remove();

    x.domain(d3.extent(data, function(d) { return d.year; }));
    y.domain(d3.extent(data, function(d) { return d.total; }));

    g.append("g")
        .attr("transform", "translate(0," + height + ")")
        .call(d3.axisBottom(x))
        .select(".domain")
        .remove();

    g.append("g")
        .call(d3.axisLeft(y))
        .append("text")
        .attr("fill", "#000")
        .attr("transform", "rotate(-90)")
        .attr("y", 6)
        .attr("dy", "0.71em")
        .attr("text-anchor", "end")
        .text("Number");

    g.append("path")
        .datum(data)
        .attr("fill", "none")
        .attr("stroke", "steelblue")
        .attr("stroke-linejoin", "round")
        .attr("stroke-linecap", "round")
        .attr("stroke-width", 1.5)
        .attr("d", line);
}

</script>
</body>
</html>

my_blog/data/templates/data/data_name_bkp.html
<!DOCTYPE html>
<meta charset="utf-8">
<style>

body {
  font: 10px sans-serif;
}

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.x.axis path {
  display: none;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 1.5px;
}

</style>
<body>
<p>
    <label for="your_name">Baby name: </label>
    <input id="your_name" type="text" name="your_name" value="Daniel">
    <input type="submit" value="OK">
</p>
<svg width="960" height="500"></svg>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script
src="https://code.jquery.com/jquery-3.2.1.min.js"
integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
crossorigin="anonymous"></script>
<script>
    var svg = d3.select("svg"),
    margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = +svg.attr("width") - margin.left - margin.right,
    height = +svg.attr("height") - margin.top - margin.bottom,
    g = svg.append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");

    //var parseDate = d3.time.format("%Y-%m-%d").parse; // for dates like "2014-01-01"
    //var parseDate = d3.time.format("%Y-%m-%dT00:00:00Z").parse;  // for dates like "2014-01-01T00:00:00Z"
    var parseTime = d3.timeParse("%Y");

    var x = d3.scaleTime()
        .rangeRound([0, width]);

    var y = d3.scaleLinear()
        .rangeRound([height, 0]);

    var line = d3.line()
        .x(function(d) { return x(d.year); })
        .y(function(d) { return y(d.total); });

    //console.log(babyname);
    //console.log(updated_url);



    g.append("g")
        .attr("transform", "translate(0," + height + ")")
        .call(d3.axisBottom(x))
        .select(".domain")
        .remove();

    g.append("g")
        .call(d3.axisLeft(y))
        .append("text")
        .attr("fill", "#000")
        .attr("transform", "rotate(-90)")
        .attr("y", 6)
        .attr("dy", "0.71em")
        .attr("text-anchor", "end")
        .text("Number");

$(document).ready(function() {

    $('#your_name').keyup(function() {
        //console.log($(this).val());
        var updated_url = 'api/' + $(this).val() + '/sum_by_sex_year/';
        //console.log(updated_url);
        $.ajax({

            // The URL for the request
            url: 'api/' + $(this).val() + '/sum_by_sex_year/',

            // The data to send (will be converted to a query string)
            //data: {
            //    id: 123
            //},

            // Whether this is a POST or GET request
            type: "GET",

            // The type of data we expect back
            dataType : "json",
            })
            // Code to run if the request succeeds (is done);
            // The response is passed to the function
            .done(function( json ) {
                //console.log( json );
                var post_data = json;
                drawChart(post_data);
            })
            // Code to run if the request fails; the raw request and
            // status codes are passed to the function
            .fail(function( xhr, status, errorThrown ) {
                alert( "Sorry, there was a problem!" );
                console.log( "Error: " + errorThrown );
                console.log( "Status: " + status );
                console.dir( xhr );
            })
            // Code to run regardless of success or failure;
            //.always(function( xhr, status ) {
            //    alert( "The request is complete!" );
        });
    });
    //console.log(babyname);
//});


//babyname = document.getElementById("your_name").value;

//updated_url = 'api/' + babyname + '/sum_by_sex_year/'



function drawChart(data){
    g.select("path").remove();

    x.domain(d3.extent(data, function(d) { return d.year; }));
    y.domain(d3.extent(data, function(d) { return d.total; }));

    g.append("path")
    .datum(data)
    .attr("fill", "none")
    .attr("stroke", "steelblue")
    .attr("stroke-linejoin", "round")
    .attr("stroke-linecap", "round")
    .attr("stroke-width", 1.5)
    .attr("d", line);


}

</script>
</body>
</html>

my_blog/home/templates/home/home_index_page.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load wagtailcore_tags %}
{% load wagtailcore_tags wagtailimages_tags %}
{% block body_class %}template-blogindexpage{% endblock %}


{% block content %}
    {% for post in blogpages %}
        {% with post=post.specific %}
            <h2><a href="{% pageurl post %}">{{ post.title }}</a></h2>
            <p>{{ post.date|date:'Y年m月j日'}}</p>
            
            {% with post.main_image as main_image %}
                {% if main_image %}{% image main_image fill-660x400 %}{% endif %}
            {% endwith %}
            <hr>
            <!--
            <p>{{ post.intro }}</p>
            -->
            {{ post.body|richtext|truncatechars:150 }}
            <span style="font-weight:bold"><a href="{% pageurl post %}">阅读原文</a></span>
        {% endwith %}
    {% endfor %}
{% endblock %}

my_blog/home/templates/home/home_page.html
{% extends "base.html" %}

{% load static from staticfiles %}
{% load wagtailcore_tags %}
{% load wagtailcore_tags wagtailimages_tags %}
{% block body_class %}template-homepage{% endblock %}

{% block content %}
<!--
    <h1>Welcome to your new Wagtail site!</h1>

    <p>You can access the admin interface <a href="{% url 'wagtailadmin_home' %}">here</a> (make sure you have run "./manage.py createsuperuser" in the console first).</p>

    <p>If you haven't already given the documentation a read, head over to <a href="http://docs.wagtail.io/">http://docs.wagtail.io</a> to start building on Wagtail</p>
-->
<h2>{{ page.title }}</h2>

<!--
<p class="meta">{{ page.date }}</p>

<div class="intro">{{ page.intro }}</div>-->

<p>{{ page.body|richtext }}</p>

<!---
{% for item in page.gallery_images.all %}
    <div style="float: left; margin: 10px">
        {% image item.image fill-320x240 %}
        <p>{{ item.caption }}</p>
    </div>
{% endfor %}
-->
<span style="font-weight:bold"><a href="{{ page.get_parent.url }}">返回首页</a></p>
{% endblock %}

my_blog/myblog/templates/base.html
{% load static wagtailuserbar %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>
            {% block title %}
                {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
            {% endblock %}
            {% block title_suffix %}
                {% with self.get_site.site_name as site_name %}
                    {% if site_name %}- {{ site_name }}{% endif %}
                {% endwith %}
            {% endblock %}
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/myblog.css' %}">

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}

        <link rel="stylesheet" type="text/css" href="{% static 'css/fontello.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">


        <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>


        <script>
                $(document).ready(function () {
                    $('#side-nav-iwrapper').width($('.side-nav').width());
        
                    $(window).resize(function () {
                        $('#side-nav-iwrapper').width($('.side-nav').width());
                    });
        
                    var $container = $('.projects-row');
                    render_portfolio($container);
                    $container.imagesLoaded(function() {
                        $container.packery({
                            itemSelector: '.project-card',
                            columnWidth: '.project-card',
                            gutter: 0,
                        });
                    });
                });
            </script>
    
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    
            ga('create', 'UA-41030351-2', 'auto');
            ga('send', 'pageview');
        </script>
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% wagtailuserbar %}


        <header class="visible-xs visible-sm">
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#fix-top-nav">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
        
                    <div class="collapse navbar-collapse" id="fix-top-nav">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="/">杂记</a></li>
                            <li><a href="/data/">数据</a></li>
                            <li><a href="/music/">音乐</a></li>
                            <li><a href="/resume/">经历</a></li>
                            <li><a href="https://github.com/YingsenMao">代码</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        
        <div class="container">
            <div class="row content-row">
                <div class="col-xs-12 col-md-3 side-nav">
                    <div id="side-nav-iwrapper" data-spy="affix">
                        <img src="{% static 'image/head.gif' %}" style="width:60%;height:60%;" alt="skiing selfie" class="img-responsive img-circle profile-img">
        
                        <h1 class="name">Daniel Mao</h1>
                        <h2 class="blurb">Dreamer and Bloger. Guitarist and Programmer</h2>
        
                        <nav class="hidden-sm hidden-xs">
                            <ul class="vertical-nav">
                                <li class="active"><a href="/">杂记</a></li>
                                <li><a href="/data/">数据</a></li>
                                <li><a href="/music/">音乐</a></li>
                                <li><a href="/resume/">经历</a></li>
                                <li><a href="https://github.com/YingsenMao">代码</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-xs-12 col-md-9 body-content">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        {# Global javascript #}
        <script type="text/javascript" src="{% static 'js/myblog.js' %}"></script>

        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>